## Universidad Nacional de Colombia
## Diplomado en IA y AP
### Juan Pablo Mojica Macías

## Canaización de Datos con Tensorflow

In [26]:
#Importación de librerias
import tensorflow as tf
import numpy as np

## Construcción de algunos Tensores

In [27]:
#Tensor de dimensión 0
tensor0=tf.constant(6)
print(tensor0)

tf.Tensor(6, shape=(), dtype=int32)


In [28]:
# Tensor de dimesión 3
tensor3=tf.constant([3,5,7])
print(tensor3)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)


In [29]:
# Tensor de dimensión 2-3
tensor23=tf.constant([[2,4,6],[8,10,12]])
print(tensor23)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [30]:
# Tensor de dimensión 2-3-5: ([[[5elementos],[5elementos],[5elementos]],[[5elmentos],[5elementos],[5elementos]]]) 
tensor235=tf.constant([[[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]],[[4,4,4,4,4],[5,5,5,5,5],[6,6,6,6,6]]])
print(tensor235)

tf.Tensor(
[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]], shape=(2, 3, 5), dtype=int32)


In [31]:
print(tensor235.numpy())
print('\n',tensor235.numpy().shape)
print('\n',tensor235.shape)

[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]]

 (2, 3, 5)

 (2, 3, 5)


### Álgebra de Tensores

In [32]:
#Consruimos dos tensores de la mismas dimensión
a=tf.constant([[1,3,5],[2,4,6]])
b=tf.constant([[1,2,3],[4,5,6]])

In [33]:
# Suma de tensores
suma=tf.add(a,b)
print(suma)

# O alternativamente
print('\n', a+b)

tf.Tensor(
[[ 2  5  8]
 [ 6  9 12]], shape=(2, 3), dtype=int32)

 tf.Tensor(
[[ 2  5  8]
 [ 6  9 12]], shape=(2, 3), dtype=int32)


In [34]:
# Producto de tensores:
prodc=tf.multiply(a,b)
print(prodc)

# O también
print('\n', a*b)

tf.Tensor(
[[ 1  6 15]
 [ 8 20 36]], shape=(2, 3), dtype=int32)

 tf.Tensor(
[[ 1  6 15]
 [ 8 20 36]], shape=(2, 3), dtype=int32)


In [35]:
# Producto de tensores matricialmente cos tensores conformables:
x=tf.constant([[2,6,5],[4,9,5]])
y=tf.constant([[2,1],[9,5],[7,8]])
prodt=tf.matmul(x,y)
print(x)
print('\n',y)
print('\n',prodt)

# También podemos hacer
print('\n', x@y)

tf.Tensor(
[[2 6 5]
 [4 9 5]], shape=(2, 3), dtype=int32)

 tf.Tensor(
[[2 1]
 [9 5]
 [7 8]], shape=(3, 2), dtype=int32)

 tf.Tensor(
[[ 93  72]
 [124  89]], shape=(2, 2), dtype=int32)

 tf.Tensor(
[[ 93  72]
 [124  89]], shape=(2, 2), dtype=int32)


### Funciones de Reducción

In [36]:
p=tf.constant([[2.0,1.0],[6.0,9.0]])
print(p)

# Identificamos el elemento mayor dentro del tensor:
print('\nELEMENTO MAYOR:',tf.reduce_max(p))
# Identificamos el elemento menor dentro del tensor:
print('\nELEMENTO MENOR:',tf.reduce_min(p))
# Calculamos el promedio de los componentes del tensor:
print('\nPROMEDIO DE LOS ELEMENTOS:',tf.reduce_mean(p))
# Identificamos la posición del elemento mayor dentro del tensor:
print('\nPOSICIÓN ELEMENTO MAYOR:',tf.argmax(p))
# Aplica la función de activación SOFTMAX a los componentes del tensor exp(e[i,j])/sum(exp(e[i,]))
print('\nSOFTMAX:\n',tf.nn.softmax(p))
# Se suman las probabilidades obtenidas con la función SOFTMAX para verificar que da 1:
print('\nSUMA PROBABILIDADES SOFTMAX:',tf.reduce_sum(tf.nn.softmax(p),axis=1),"\n")

tf.Tensor(
[[2. 1.]
 [6. 9.]], shape=(2, 2), dtype=float32)

ELEMENTO MAYOR: tf.Tensor(9.0, shape=(), dtype=float32)

ELEMENTO MENOR: tf.Tensor(1.0, shape=(), dtype=float32)

PROMEDIO DE LOS ELEMENTOS: tf.Tensor(4.5, shape=(), dtype=float32)

POSICIÓN ELEMENTO MAYOR: tf.Tensor([1 1], shape=(2,), dtype=int64)

SOFTMAX:
 tf.Tensor(
[[0.7310586  0.26894143]
 [0.04742587 0.95257413]], shape=(2, 2), dtype=float32)

SUMA PROBABILIDADES SOFTMAX: tf.Tensor([1. 1.], shape=(2,), dtype=float32) 



### Tipo, Forma y Dimensión

In [37]:
ts=tf.constant([[[9,4,2,5,9],[1,4,5,0,6]],
                    [[3,7,7,1,2],[2,4,2,5,1]],
                    [[1,5,23,6,1],[10,7,0,16,7]]])
print('TIPO: ',ts.dtype)
print('\nFORMA: ',ts.shape)
print('\nDIMENSIÓN: ',ts.ndim)
print('\nDIMENSIÓN DE UN COMPONENTE: ',ts.shape[1])
print('\nNÚMERO DE ELEMENTOS: ',tf.size(ts.numpy()))

TIPO:  <dtype: 'int32'>

FORMA:  (3, 2, 5)

DIMENSIÓN:  3

DIMENSIÓN DE UN COMPONENTE:  2

NÚMERO DE ELEMENTOS:  tf.Tensor(30, shape=(), dtype=int32)


### Manejo de Índices

In [38]:
# manejo de índices
ts=tf.constant([10,4,14,15,3,4,10,19,19,6])
print(ts)
print("\nPIMER ELEMENTO: ", ts[0])
print("\nQUINTO ELEMENTO: ", ts[4])
print("\nÚLTIMO EMENTO: ", ts[-1].numpy())
print('\nTODOS LOS ELEMENTOS: ', ts[:].numpy())
print('\nELEMENTOS ANTES DE LA POSICIÓN 5: ', ts[:5].numpy())
print('\nELEMENTOS DESPUÉS DE LA POSICIÓN 5: ', ts[5:].numpy())
print('\nDESDER LA POSICIÓN 4 HASTA LA POSICIÓN 6: ', ts[4:7].numpy())
print('\nELEMENTOS EN LA POSICIÓN IMPAR: ', ts[0::2].numpy())
print('\nELEMENTOS INVIRTIENDO EL ORDEN: ', ts[::-1].numpy())

tf.Tensor([10  4 14 15  3  4 10 19 19  6], shape=(10,), dtype=int32)

PIMER ELEMENTO:  tf.Tensor(10, shape=(), dtype=int32)

QUINTO ELEMENTO:  tf.Tensor(3, shape=(), dtype=int32)

ÚLTIMO EMENTO:  6

TODOS LOS ELEMENTOS:  [10  4 14 15  3  4 10 19 19  6]

ELEMENTOS ANTES DE LA POSICIÓN 5:  [10  4 14 15  3]

ELEMENTOS DESPUÉS DE LA POSICIÓN 5:  [ 4 10 19 19  6]

DESDER LA POSICIÓN 4 HASTA LA POSICIÓN 6:  [ 3  4 10]

ELEMENTOS EN LA POSICIÓN IMPAR:  [10 14  3 10 19]

ELEMENTOS INVIRTIENDO EL ORDEN:  [ 6 19 19 10  4  3 15 14  4 10]


In [39]:
t=tf.constant([[2,3,4],[1,7,9]])
print('TENSOR: ', t)

print('\nCOMPONENTE EN LA POSICIÓN 0-1 = ',t[0,1].numpy())
print('\nPRIMERA FILA: ', t[0,:].numpy())
print('\nPRIMERA COLUMNA: ', t[:,0].numpy())
print('\nÚLTIMA COLUMNA: ', t[:,-1].numpy())
print('\nPRIMER ELEMENTO DE LA ÚLTIMA COLUMNA: ', t[0,-1].numpy())
print('\nSALTAR LA PRIMERA COLUMNA:\n', t[:,1:].numpy())

TENSOR:  tf.Tensor(
[[2 3 4]
 [1 7 9]], shape=(2, 3), dtype=int32)

COMPONENTE EN LA POSICIÓN 0-1 =  3

PRIMERA FILA:  [2 3 4]

PRIMERA COLUMNA:  [2 1]

ÚLTIMA COLUMNA:  [4 9]

PRIMER ELEMENTO DE LA ÚLTIMA COLUMNA:  4

SALTAR LA PRIMERA COLUMNA:
 [[3 4]
 [7 9]]


In [40]:
# Creamos un vector 3-2-5 para ilustrar
ten=tf.constant([[[1,2,3,4,5],[4,4,6,6,7]],[[8,9,1,2,3],[12,8,10,21,20]],[[2,4,6,8,10],[30,31,32,33,12]]])
print(ten.shape,'\n')
print(ten.numpy())
print('PRIMERA CAPA\n', ten[0,:,:])
print('\nPRIMERA CAPA\n', ten[0])
print('\nSEGUNDA CAPA\n', ten[1])
print('\nTERCERA CAPA\n', ten[2])

(3, 2, 5) 

[[[ 1  2  3  4  5]
  [ 4  4  6  6  7]]

 [[ 8  9  1  2  3]
  [12  8 10 21 20]]

 [[ 2  4  6  8 10]
  [30 31 32 33 12]]]
PRIMERA CAPA
 tf.Tensor(
[[1 2 3 4 5]
 [4 4 6 6 7]], shape=(2, 5), dtype=int32)

PRIMERA CAPA
 tf.Tensor(
[[1 2 3 4 5]
 [4 4 6 6 7]], shape=(2, 5), dtype=int32)

SEGUNDA CAPA
 tf.Tensor(
[[ 8  9  1  2  3]
 [12  8 10 21 20]], shape=(2, 5), dtype=int32)

TERCERA CAPA
 tf.Tensor(
[[ 2  4  6  8 10]
 [30 31 32 33 12]], shape=(2, 5), dtype=int32)


In [41]:
x = tf.constant([[1],[2],[3]])
print('FORMA: ', x.shape)
print('\nFORMA COMO LISTA: ',x.shape.as_list(),'\n')
reshaped = tf.reshape(x,[1,3])
print(reshaped.numpy(),'\n')
print(x.numpy())
print("Tensor actual: \n", tensor.numpy())
flat = tf.reshape(tensor, [-1])
print("\n TENSOR APLANADO: \n", flat.numpy())
print(tensor.shape.as_list(),'\n')
print(tf.reshape(tensor, [2*3,5]),'\n')
print(tf.reshape(tensor, [2,3*5]),'\n')
print(tf.reshape(tensor, [-1,5]),'\n')
print(tf.reshape(tensor, [3,-1]),'\n')
print(tf.reshape(tensor, [3,2,5]),'\n')

FORMA:  (3, 1)

FORMA COMO LISTA:  [3, 1] 

[[1 2 3]] 

[[1]
 [2]
 [3]]
Tensor actual: 
 [[[ 9  4  2  5  9]
  [ 1  4  5  0  6]]

 [[ 3  7  7  1  2]
  [ 2  4  2  5  1]]

 [[ 1  5 23  6  1]
  [10  7  0 16  7]]]

 TENSOR APLANADO: 
 [ 9  4  2  5  9  1  4  5  0  6  3  7  7  1  2  2  4  2  5  1  1  5 23  6
  1 10  7  0 16  7]
[3, 2, 5] 

tf.Tensor(
[[ 9  4  2  5  9]
 [ 1  4  5  0  6]
 [ 3  7  7  1  2]
 [ 2  4  2  5  1]
 [ 1  5 23  6  1]
 [10  7  0 16  7]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 9  4  2  5  9  1  4  5  0  6  3  7  7  1  2]
 [ 2  4  2  5  1  1  5 23  6  1 10  7  0 16  7]], shape=(2, 15), dtype=int32) 

tf.Tensor(
[[ 9  4  2  5  9]
 [ 1  4  5  0  6]
 [ 3  7  7  1  2]
 [ 2  4  2  5  1]
 [ 1  5 23  6  1]
 [10  7  0 16  7]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 9  4  2  5  9  1  4  5  0  6]
 [ 3  7  7  1  2  2  4  2  5  1]
 [ 1  5 23  6  1 10  7  0 16  7]], shape=(3, 10), dtype=int32) 

tf.Tensor(
[[[ 9  4  2  5  9]
  [ 1  4  5  0  6]]

 [[ 3  7  7  1  2]
  [ 2  4  2  5

In [42]:
#La función 'cast':
f64_tensor = tf.constant([9.0, 4.0, 7.0], dtype = tf.float64)
print(f64_tensor,'\n')

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16)
print(f16_tensor,'\n')

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor,'\n')

tf.Tensor([9. 4. 7.], shape=(3,), dtype=float64) 

tf.Tensor([9. 4. 7.], shape=(3,), dtype=float16) 

tf.Tensor([9 4 7], shape=(3,), dtype=uint8) 



### Radiodifusión

In [43]:
a = tf.constant([2, 4 ,6])
b = tf.constant(5)
c = tf.constant([5, 5 ,5])

# Podemos producir el mismo resultado usando la siguiente sintaxis:
print(tf.multiply(a,5),'\n')
print(a*b,'\n')
print(a*c,'\n')

a = tf.reshape(a, [3,1])
b = tf.constant([2,4,6,8,10])
print(a, '\n')
print(b, '\n')
print(tf.multiply(a,b)) 

tf.Tensor([10 20 30], shape=(3,), dtype=int32) 

tf.Tensor([10 20 30], shape=(3,), dtype=int32) 

tf.Tensor([10 20 30], shape=(3,), dtype=int32) 

tf.Tensor(
[[2]
 [4]
 [6]], shape=(3, 1), dtype=int32) 

tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32) 

tf.Tensor(
[[ 4  8 12 16 20]
 [ 8 16 24 32 40]
 [12 24 36 48 60]], shape=(3, 5), dtype=int32)


In [44]:
# Creamos un tensor 3-3 a partir de un componente
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


### Tensores Irregulares

In [45]:
ragged_list=[
    [0,1,2,3],
    [4],
    [5,6,7],
    [8,9]
]
ragged_t = tf.ragged.constant(ragged_list)

print(ragged_t.shape)

(4, None)


### Tensores de String

In [46]:
tt=tf.constant("Creamos un tensor con texto")
print(tt)

tf.Tensor(b'Creamos un tensor con texto', shape=(), dtype=string)


In [47]:
tt=tf.constant(["Creamos un tensor con texto",
               "Texto 2",
               "Texto 3",
               "Emoji",
               "😁"])
print(tt,'\n')
print('\n',tf.strings.split(tt))

tf.Tensor(
[b'Creamos un tensor con texto' b'Texto 2' b'Texto 3' b'Emoji'
 b'\xf0\x9f\x98\x81'], shape=(5,), dtype=string) 


 <tf.RaggedTensor [[b'Creamos', b'un', b'tensor', b'con', b'texto'], [b'Texto', b'2'], [b'Texto', b'3'], [b'Emoji'], [b'\xf0\x9f\x98\x81']]>


In [48]:
tt_split = tf.strings.split(tt)
for i in tt_split:
    print(i)

tf.Tensor([b'Creamos' b'un' b'tensor' b'con' b'texto'], shape=(5,), dtype=string)
tf.Tensor([b'Texto' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Texto' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'Emoji'], shape=(1,), dtype=string)
tf.Tensor([b'\xf0\x9f\x98\x81'], shape=(1,), dtype=string)


In [49]:
# Podemos convertir un string en número:
tt = tf.constant("8 15 20.2")

print(tf.strings.to_number(tf.strings.split(tt, " ")))

tf.Tensor([ 8.  15.  20.2], shape=(3,), dtype=float32)


### Tensores Dispersos

In [50]:
# Construimos un tensor disperso
tensor_disp = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(tensor_disp, "\n")

# Ahora lo convertimos en un tensor denso
print(tf.sparse.to_dense(tensor_disp))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
